"""Find a route to Act!'s EIC Contact field, which the contact payload hides.

THE PROBLEM. Act! defines two fields with nearly the same name:

    REFERREDBY                   display "EIC Contact"   picklist of 13 reps
    CUST_ReferredBy_094317334    display "Referred By"   5 free-text sources

The REST contact resource serialises only one of them, under `referredBy`, and
it is the CUSTOM one -- its 885 populated values are that field's picklist
items (`Greg Hillard`, `Branch List 10.7.2010`, `self`). The core column is
shadowed by the name collision and never appears, on any of 47,469 records.
`$select=REFERREDBY` does not reach past it either: Joe Bennick is `SH` in the
Excel export and `null` through the API.

That column is the relationship owner for 27,128 advisors, and it is the last
thing keeping build_contacts.py on a CRM export from 2026-06-30 instead of the
live JSON.

WHAT THIS DOES. Nothing but read. Act!'s dynamic-list machinery queries records
by field criteria, and `api/dynamic-list/metadata` states which fields it can
query and under what table/column names -- where REFERREDBY does appear, as
"EIC Contact" on TBL_CONTACT, carrying all thirteen codes. So the column is
QUERYABLE even though it will not SERIALISE, and one preview per code yields
the owner map.

--preview CODE probes for the request shape. The Swagger entry for
contact-preview is autogenerated ODataQueryOptions boilerplate describing the
framework rather than the request, so the body has to be established
empirically, from Act!'s own operator vocabulary and its error messages.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from act_client import Act, ActError, BASE
from contact_provenance import (SCHEMA_VERSION, atomic_create_json,
                                json_array_facts, json_array_ids,
                                pull_id_from_path, utc_pull_id)

ROOT = Path(__file__).resolve().parents[1]
INTERIM = ROOT / "data" / "interim"
RAW = ROOT / "data" / "raw"


def stamp() -> str:
    """Immutable UTC pull id shared by both halves of one Act export."""
    return utc_pull_id()

# The codes, from api/metadata/contact/fields. Kept here so the report can say
# which of them a picklist accounts for -- that is what tells the EIC Contact
# field apart from the custom "Referred By" it collides with.
CODES = {
    "AW": "Allen White", "DM": "Dennis McKinney", "JPP": "Paul Power",
    "KT": "Keith Telesca", "MK": "Matt Keeter", "RTI": "Terry Irrgang",
    "SB": "Sam Borland", "SH": "Steve Halley", "SZ": "Steve Zimmerman",
    "TL": "Tate Lambeth", "WAB": "Andrew Bruner", "Other": "Other",
}

COLUMN, TABLE = "REFERREDBY", "TBL_CONTACT"

# The criterion Act! accepts, established by probing and then confirmed against
# a known answer: 5,691 contacts came back for SH against 5,690 in the June
# Excel export, agreeing on 4,931 of 4,933 addresses, with the six differences
# being eight weeks of reassignment. Joe Bennick, whose code we already knew,
# is in the result.
#
# The vocabulary is not guessable and every part of it matters: `EqualTo`, not
# `Equals`; `tableName`/`columnName`, not `table`/`column`; and each value is an
# XmlValue object, not a bare string. The body is a BARE ARRAY of these.
CRITERION = {
    "tableName": TABLE,
    "columnName": COLUMN,
    "columnDisplayName": "EIC Contact",
    "tableDisplayName": "Contacts",
    "domain": "String",
    "operator": "EqualTo",
    "leftParentheses": 0,
    "rightParentheses": 0,
    # End = "no further criterion follows". And/Or would join another row.
    "logicalOperator": "End",
}


def criteria_body(value):
    """The request body for 'EIC Contact is exactly `value`'."""
    return [dict(CRITERION, values=[{"type": "String", "dataItem": value}])]


def entities(payload):
    """The metadata arrives as one entity or a list of them; normalise to a list.

    Act!'s responses alternate between a bare array and an OData envelope with
    the rows under `value`, depending on the endpoint. Both are handled here so
    a shape change reads as an empty result rather than a TypeError.
    """
    if isinstance(payload, dict):
        payload = payload.get("value") or payload.get("items") or [payload]
    return [e for e in (payload or []) if isinstance(e, dict)]


def rows_of(payload):
    """Rows out of a bare array, an OData envelope, or an items wrapper."""
    if isinstance(payload, list):
        return payload
    return (payload or {}).get("value") or (payload or {}).get("items") or []


def strict_rows_of(payload):
    """Return preview rows, rejecting an undocumented response shape."""
    if isinstance(payload, list):
        rows = payload
    elif isinstance(payload, dict) and isinstance(payload.get("value"), list):
        rows = payload["value"]
    elif isinstance(payload, dict) and isinstance(payload.get("items"), list):
        rows = payload["items"]
    else:
        raise ActError("dynamic-list preview returned no recognized row array")
    if any(not isinstance(row, dict) for row in rows):
        raise ActError("dynamic-list preview returned a non-object row")
    return rows


def interesting(field):
    """Does this field look like either half of the REFERREDBY collision?"""
    blob = " ".join(str(field.get(k) or "") for k in ("name", "column", "table")).lower()
    return "referred" in blob or "eic" in blob


def picklist_values(field):
    """The picklist's values, however Act! chose to shape them this time.

    api/metadata/contact/fields returns objects with value/description;
    api/dynamic-list/metadata returns bare strings. Assuming whichever shape
    turned up first is how this crashed the first time it ran.
    """
    values = set()
    for item in ((field.get("list") or {}).get("items")) or []:
        if isinstance(item, dict):
            item = item.get("value") or item.get("name") or ""
        item = str(item or "").strip()
        if item:
            values.add(item)
    return values


def owner_codes_from_metadata(act):
    """Return the live EIC Contact vocabulary or fail before querying.

    A hard-coded list can silently become incomplete when an owner code is
    added in Act. The metadata is therefore the authority for which values a
    complete pull must query; ``CODES`` supplies only their display labels.
    """
    payload = act.get("api/dynamic-list/metadata")
    matches = []
    for entity in entities(payload):
        for field in entity.get("fields") or []:
            if not isinstance(field, dict):
                continue
            table = str(field.get("table") or field.get("tableName") or "")
            column = str(field.get("column") or field.get("columnName") or "")
            if table.upper() == TABLE and column.upper() == COLUMN:
                matches.append(field)
    if len(matches) != 1:
        raise ActError(
            f"expected one {TABLE}.{COLUMN} metadata field, found {len(matches)}")
    live = picklist_values(matches[0])
    if not live:
        raise ActError(f"{TABLE}.{COLUMN} metadata has no owner-code picklist")
    unknown = live - set(CODES)
    if unknown:
        raise ActError(
            "Act contains unlabelled EIC owner codes; update CODES before pulling: "
            + ", ".join(sorted(unknown)))
    return sorted(live)


def indent(blob, width=3):
    """Pretty JSON, shifted right so it reads as belonging to its heading."""
    pad = " " * width
    return pad + json.dumps(blob, indent=2, default=str).replace("\n", "\n" + pad)


# ---------------------------------------------------------------------------
# Finding the request shape.
#
# The path endpoint's own Swagger entry is autogenerated ODataQueryOptions
# boilerplate and says nothing about the body. The DEFINITIONS section of the
# same document does: act.web.api.models.Lists.Criteria carries the property
# names, the operator enum, and the XmlValue shape of each comparison value.
# Reading that beat guessing, which produced five identical 500s.
#
# api/dynamic-list/operators confirms which operators a String column actually
# accepts. (api/groups was tried too, on the theory that a criteria-driven group
# would carry a real example; 25 groups exposed no criteria object, so that call
# is not made any more.)
#
# Everything here reads. The preview endpoint queries and returns matches; it
# creates nothing, which is what makes trial and error acceptable at all.
# ---------------------------------------------------------------------------
def candidate_bodies(value):
    """Bodies to try, built from act.web.api.models.Lists.Criteria in the spec.

    The first round guessed and got five identical 500s, all saying the same
    useful thing:

        Cannot deserialize the current JSON object into type
        'List`1[act.web.api.models.Lists.Criteria]' because the type requires
        a JSON array

    So the body is a BARE ARRAY of Criteria -- no envelope, no "type": "Contacts"
    wrapper. The model also settles the vocabulary that guessing got wrong:
    the operator is `EqualTo`, not `Equals`; the property names are tableName and
    columnName, not table and column; `domain` carries the data type; and each
    value is an XmlValue object with type/dataItem rather than a bare string.

    What the spec does NOT settle is whether columnId is required (dynamic-list
    metadata does not return one) and what XmlValue.type wants. Those are the
    only two things these variants still differ on.
    """
    base = dict(CRITERION)
    return [
        ("array/XmlValue type=String", criteria_body(value)),
        ("array/XmlValue dataItem only",
         [dict(base, values=[{"dataItem": value}])]),
        ("array/bare string value",
         [dict(base, values=[value])]),
        ("array/minimal",
         [{"tableName": TABLE, "columnName": COLUMN, "domain": "String",
           "operator": "EqualTo", "logicalOperator": "End",
           "values": [{"type": "String", "dataItem": value}]}]),
        ("array/columnId empty",
         [dict(base, columnId="", values=[{"type": "String", "dataItem": value}])]),
    ]


def show_operators(act):
    """What String columns may be compared with. Only String matters here.

    The endpoint returns every data type at once, which is several screens of
    date arithmetic nobody needs for a picklist lookup.
    """
    print("\n--- operators available on String columns ---------------------")
    try:
        payload = act.get("api/dynamic-list/operators")
    except ActError as e:
        print(f"  unavailable: {str(e)[:160]}")
        return
    for group in rows_of(payload):
        if not isinstance(group, dict) or group.get("dataType") != "String":
            continue
        for op in group.get("operators") or []:
            print(f"  {str(op.get('name')):<26} enum={op.get('operatorEnum')}")
        return
    print("  (no String operators returned)")


def probe_preview(act, value, save):
    show_operators(act)
    # The group probe is gone: 25 groups exposed no criteria object, and the
    # Criteria model came from the Swagger definitions instead. No point
    # spending a call on a question already answered.

    print(f"\n--- contact-preview, EIC Contact = {value!r} -------------------")
    for label, body in candidate_bodies(value):
        status, payload = act.post("api/dynamic-list/contact-preview", body,
                                   allow_error=True)
        if status != 200:
            # The error body is the useful part: it names what failed to bind.
            # Printed long, and exceptionMessage first -- the previous run cut
            # off mid-sentence exactly where the answer was.
            detail = payload
            if isinstance(payload, dict):
                detail = (payload.get("exceptionMessage") or payload.get("message")
                          or json.dumps(payload, default=str))
            print(f"  [{status}] {label}:\n      {str(detail)[:600]}")
            continue

        rows = rows_of(payload)
        print(f"  [{status}] {label}: {len(rows)} row(s) MATCHED")
        if rows:
            print(indent(rows[0])[:900])
            names = " ".join(str(r.get("fullName") or "") for r in rows
                             if isinstance(r, dict))
            if "Bennick" in names:
                print("   ^ Joe Bennick is in this result -- mapping confirmed "
                      "against the value we already knew from the Excel export.")
        if save:
            INTERIM.mkdir(parents=True, exist_ok=True)
            out = INTERIM / f"act_preview_{value}.json"
            out.write_text(json.dumps(payload, indent=1, default=str), encoding="utf-8")
            print(f"   [*] wrote {out}")
        print(f"\n  WORKING SHAPE: {label}")
        print(indent(body))
        return True

    print("\n  No candidate shape was accepted. The messages above name what Act!")
    print("  could not bind; that is what the next attempt should be built from.")
    return False


def extract(act, dest=None, csv_dest=None, contacts_path=None):
    """Query every code and build the owner map the contact payload cannot give.

    One preview per code. A contact should appear under exactly one -- the field
    holds a single value -- so anything appearing twice is a genuine surprise and
    is reported rather than silently resolved by whichever query ran last.

    Writes contact id -> code. The id is Act!'s own key, so this joins to the
    JSON pull directly and needs no match on name or address.

    The JSON lands in data/raw, DATED, beside the contact pull it belongs with.
    It is raw: genuinely what Act! returned, from a second endpoint. It is not
    merged into the contact file, because that file is documented as a faithful
    record of api/contacts (see docs/name_provenance.md) and splicing a second
    endpoint's result into it would make that claim false -- and would hide the
    fact that a single code's query can fail while the rest succeed.
    """
    binding = json_array_facts(Path(contacts_path), "act_contacts") \
        if contacts_path is not None else None
    contact_ids = json_array_ids(Path(contacts_path)) \
        if contacts_path is not None else frozenset()
    query_codes = owner_codes_from_metadata(act)
    assignments, names = {}, {}
    counts = {}
    for code in query_codes:
        try:
            payload = act.post("api/dynamic-list/contact-preview", criteria_body(code))
            rows = strict_rows_of(payload)
        except ActError as e:
            print(f"  {code:<6} FAILED: {str(e)[:160]}")
            counts[code] = None
            continue
        code_ids = [str(row.get("id") or "").strip() for row in rows]
        if any(not contact_id for contact_id in code_ids):
            print(f"  {code:<6} FAILED: preview returned a row without an Act id")
            counts[code] = None
            continue
        if len(set(code_ids)) != len(code_ids):
            print(f"  {code:<6} FAILED: preview returned duplicate Act ids")
            counts[code] = None
            continue
        unknown = set(code_ids) - contact_ids if binding is not None else set()
        if unknown:
            print(f"  {code:<6} FAILED: {len(unknown)} id(s) are absent from "
                  "the bound contact pull")
            counts[code] = None
            continue
        counts[code] = len(rows)
        for r in rows:
            cid = str(r.get("id") or "").strip()
            if not cid:
                continue
            assignments.setdefault(cid, set()).add(code)
            names[cid] = str(r.get("fullName") or "")
        print(f"  {code:<6} {CODES[code]:<18} {len(rows):>7,}")

    owners = {cid: next(iter(codes)) for cid, codes in assignments.items()
              if len(codes) == 1}
    conflicts = [(cid, sorted(codes), names.get(cid, ""))
                 for cid, codes in assignments.items() if len(codes) > 1]
    total = sum(v for v in counts.values() if v)
    print(f"\n  {'TOTAL':<25} {total:>7,} row(s); "
          f"{len(owners):,} distinct contacts")
    if conflicts:
        print(f"\n  [!] {len(conflicts)} contact(s) matched more than one code. "
              f"The field holds one value, so this needs a human look:")
        for cid, codes, who in conflicts[:10]:
            print(f"      {who} ({cid}) -> {', '.join(codes)}")

    if dest is not False:
        if binding is None:
            raise ActError("owner artifacts must be bound to --contacts-file")
        pull_id = pull_id_from_path(Path(contacts_path))
        out = Path(dest) if dest else (RAW / f"act_eic_contact_{pull_id}.json")
        failed_codes = sorted(code for code, count in counts.items()
                              if count is None)
        if failed_codes:
            raise ActError(
                "refusing to publish an incomplete EIC owner artifact; "
                f"failed codes: {', '.join(failed_codes)}")
        payload = {
            "schema_version": SCHEMA_VERSION,
            "pull_id": pull_id,
            "contacts_file": binding["file"],
            "contacts_sha256": binding["sha256"],
            "contacts_rows": binding["rows"],
            "complete": not failed_codes,
            "failed_codes": failed_codes,
            "expected_codes": query_codes,
            "queried_codes": sorted(code for code, count in counts.items()
                                    if count is not None),
            "built_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "source": "act api/dynamic-list/contact-preview on TBL_CONTACT.REFERREDBY",
            # Why this file exists at all, for whoever finds it in a year.
            "note": ("The EIC Contact column does not serialise through "
                     "api/contacts -- a custom field of nearly the same name "
                     "shadows it -- so it is queried instead."),
            "codes": CODES,
            "counts": counts,
            "conflicts": [{"id": c[0], "codes": c[1], "name": c[2]}
                          for c in conflicts],
            "owner_by_contact_id": owners,
        }
        atomic_create_json(out, payload, pretty=True)
        print(f"\n[*] wrote {out}")

        # The CSV is for a human to eyeball; it is derived, so it goes to
        # interim and is not dated -- there is only ever a current one.
        csv_out = Path(csv_dest) if csv_dest else (INTERIM / "act_eic_contact.csv")
        csv_out.parent.mkdir(parents=True, exist_ok=True)
        with csv_out.open("w", encoding="utf-8", newline="") as fh:
            w = csv.writer(fh)
            w.writerow(["contact_id", "full_name", "code", "owner"])
            for cid, code in sorted(owners.items(), key=lambda kv: (kv[1], names.get(kv[0], ""))):
                w.writerow([cid, names.get(cid, ""), code, CODES[code]])
        print(f"[*] wrote {csv_out}")
    return owners


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--user", required=True)
    ap.add_argument("--db", required=True)
    ap.add_argument("--base", default=BASE)
    ap.add_argument("--save", action="store_true",
                    help="write the metadata (and any preview result) to data/interim/")
    ap.add_argument("--extract", action="store_true",
                    help="query all codes and write the owner map to data/interim/ "
                         "(contact id -> code). Read-only.")
    ap.add_argument("--contacts-file",
                    help="exact act_contacts_*.json this owner query describes; "
                         "required with --extract")
    ap.add_argument("--preview", metavar="CODE",
                    help="after reporting the field, try to query contacts whose "
                         "EIC Contact is CODE (e.g. SH). Read-only: the preview "
                         "endpoint returns matches and creates nothing.")
    args = ap.parse_args()

    if args.extract:
        print("[!] Standalone owner refreshes are disabled. Run src/act_pull.py "
              "so contacts and owners are captured and published as one "
              "hash-bound immutable pair.")
        return 2

    password = os.environ.get("ACT_PASSWORD", "")
    if not password:
        print("ACT_PASSWORD is not set.\n"
              "  PowerShell:  $env:ACT_PASSWORD = 'your password in SINGLE quotes'")
        return 2

    act = Act(args.user, password, args.db, args.base)
    act.authorize()
    print(f"authorized against {act.base} as {args.user}\n")

    try:
        meta = act.get("api/dynamic-list/metadata")
    except ActError as e:
        print(f"[!] api/dynamic-list/metadata -> {str(e)[:200]}")
        return 1

    ents = entities(meta)
    print(f"{len(ents)} queryable entity type(s): "
          f"{', '.join(str(e.get('name') or e.get('type') or '?') for e in ents)}\n")

    found = []
    for ent in ents:
        label = str(ent.get("name") or ent.get("type") or "?")
        fields = ent.get("fields") or []
        print(f"  {label}: {len(fields)} queryable field(s)")
        for f in fields:
            if isinstance(f, dict) and interesting(f):
                found.append((label, f))

    if not found:
        print("\n[!] No queryable field mentions 'referred' or 'eic'.")
        return 1

    print(f"\n{len(found)} candidate field(s) -- the full definition of each, because")
    print("the table/column pair is what a preview request has to name:\n")
    for label, f in found:
        print(f"  [{label}]")
        print(indent(f))
        values = picklist_values(f)
        overlap = values & set(CODES)
        if overlap:
            print(f"   ^ THIS IS THE EIC CONTACT FIELD: its picklist carries "
                  f"{len(overlap)} of the {len(CODES)} known codes "
                  f"({', '.join(sorted(overlap)[:6])}...)")
        elif values:
            print(f"   ^ not it: picklist holds {sorted(values)[:5]}")
        print()

    if args.save:
        INTERIM.mkdir(parents=True, exist_ok=True)
        out = INTERIM / "act_dynamic_list_metadata.json"
        out.write_text(json.dumps(meta, indent=1, default=str), encoding="utf-8")
        print(f"[*] wrote {out}")

    if args.preview:
        if args.preview not in CODES:
            print(f"\n[!] {args.preview!r} is not one of the known codes: "
                  f"{', '.join(sorted(CODES))}")
            return 2
        probe_preview(act, args.preview, args.save)
        return 0

    print("Next: with the table/column names above, one contact-preview per code")
    print("gives contact id -> owner. Nothing is written to Act! by any of it.")
    print("Add --preview SH to try it.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
